### ISSUE TITLE
Unhandled property value type 'Kingsland.MofParser.Ast.ComplexValueAst'

### ISSUE THREAD

**Issue by raandree** [KingslandConsulting/Kingsland.MofParser#83]
The method `ParseMofFileInstances` throws a `NotImplementedException` when dealing with instance types.

```
Exception calling "ParseMofFileInstances" with "1" argument(s): "Unhandled property value type 'Kingsland.MofParser.Ast.ComplexValueAst'"
```

Do you have by any chance extended the parser?

This is the PowerShell code I am using and below is a MOF file to reproduce the error.

```powershell
Add-Type -Path $PSScriptRoot\MofParser\Kingsland.MofParser.dll

function Get-MofFileClasses
{
    param (
        [Parameter(Mandatory, ValueFromPipeline)]
        [string[]]$Path
    )

    begin
    {
        $mofClasses = @()
    }

    process
    {
        foreach ($p in $Path)
        {
            $p = Resolve-Path -Path $p
            $mofClasses += [Kingsland.MofParser.PowerShellDscHelper]::ParseMofFileInstances($p)
        }
    }

    end
    {
        $mofClasses
    }
}

$c = Get-MofFileClasses -Path D:\Git\DscBuildHelpersDebug\output\MOF\ClassBasedNode.mof
```

```mof
instance of CustomObject1 as $CustomObject11ref
{
Bool1 = True;
 String1 = "21Object1String1";

};

instance of ClassBasedResource2 as $ClassBasedResource21ref
{
Key = "2k1";
 ModuleVersion = "0.1.0";
 Object1 = $CustomObject11ref;
 Ensure = "Present";
 SourceInfo = "::3::1::ClassBasedResource2";
 ResourceID = "[ClassBasedResource2]2k1::[ClassBasedResources2]ClassBasedResources2";
 ModuleName = "ClassBased";

 ConfigurationName = "RootConfiguration";

};
instance of OMI_ConfigurationDocument


                    {
 Version="2.0.0";


                        MinimumCompatibleVersion = "1.0.0";


                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};


                        Author="randr";


                        GenerationDate="05/23/2024 14:06:44";


                        GenerationHost="RAANDREE0";


                        Name="MOF__ NA";


                    };
```

**Comment by mikeclayton** [comment]
Hello. Just a quick reply to let you know I've seen this issue. I'll have a proper look over the weekend and give you an update after...

**Comment by mikeclayton** [comment]
I've just published a new nuget package - v8.0.0 which is bumped to dotnet 8.

It's also got a new implementation for domain objects (Instances, Classes, etc) and a slightly different way of parsing, but it *should*  be a drop-in replacement for what you've got at the moment.

It's not 100% feature complete across the whole MOF spec, but if you give that a go and let me know if there's any problems I'll take another look...

**Comment by mikeclayton** [comment]
Closing ticket on the assumption the new release fixes it. Will re-open if there's any problems reported...

**Comment by raandree** [comment]
Thanks, @mikeclayton, the release 8.0.0 fixed the issue and I am successfully using your solution in [Microsoft365DscWorkshop](https://github.com/raandree/Microsoft365DscWorkshop).

**Comment by mikeclayton** [comment]
All good.

I keep meaning to switch / dual licence under the MIT license as well - I'll try to do that as part of the dotnet 9 upgrade when it's time for that :-).
